### ISSUE TITLE
SublimeHaskell crashing on OS X

### ISSUE THREAD

**Issue by xldenis** [SublimeHaskell/SublimeHaskell#307]
I've tried using SublimeHaskell a few times over the past few months and it's never worked, but it seems to be getting less broken each time! 😄 . Anyways, I'm getting errors like this whenever I try running any command in SublimeHaskell. 

```
<hsdev stdout> 05/03/17 22:09:11 -0600  WARN  <socket: 28>/<socket: 28>> Invalid request {"no-file":true,"id":"19","command":"types","ghc-opts":["-i /my_user_path/Code/xldenis/my_project"],"files":[{"file":"/my_user_path/Code/xldenis/my_project/src/Todo.hs","contents":null}]}
<hsdev stdout> 05/03/17 22:09:11 -0600  INFO  update> writing cache to /my_user_path/Library/Application Support/Sublime Text 3/Cache/SublimeHaskell/hsdev
<hsdev stdout> 05/03/17 22:09:11 -0600  INFO  update> cache saved to /my_user_path/Library/Application Support/Sublime Text 3/Cache/SublimeHaskell/hsdev
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "/my_user_path/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/filter_command.py", line 33, in run
    with ProcHelper(self.indenter, sel_str) as p:
NameError: global name 'ProcHelper' is not defined
<hsdev stdout> 05/03/17 22:13:45 -0600  INFO  <socket: 42>> <socket: 42> connected
<hsdev stderr> hsdev: shutdown: invalid argument (Socket is not connected)
<hsdev stdout> 05/03/17 22:13:45 -0600  INFO  <socket: 42>> <socket: 42> disconnected
<hsdev stdout> 05/03/17 22:13:51 -0600  INFO  <socket: 42>> <socket: 42> connected
<hsdev stderr> hsdev: shutdown: invalid argument (Socket is not connected)
<hsdev stdout> 05/03/17 22:13:51 -0600  INFO  <socket: 42>> <socket: 42> disconnected
<hsdev stdout> 05/03/17 22:14:05 -0600  INFO  <socket: 42>> <socket: 42> connected
<hsdev stdout> 05/03/17 22:14:05 -0600  TRACE ghc/types> restarting ghc session with: -no-user-package-db -package-db /my_user_path/.stack/snapshots/x86_64-osx/lts-8.3/7.10.3/pkgdb -package-db /my_user_path/Code/xldenis/my_project/.stack-work/install/x86_64-osx/lts-8.3/7.10.3/pkgdb
<hsdev stdout> 05/03/17 22:14:05 -0600  TRACE ghc/types> setting ghc options: -no-user-package-db -package-db /my_user_path/.stack/snapshots/x86_64-osx/lts-8.3/7.10.3/pkgdb -package-db /my_user_path/Code/xldenis/my_project/.stack-work/install/x86_64-osx/lts-8.3/7.10.3/pkgdb
<hsdev stderr> hsdev: shutdown: invalid argument (Socket is not connected)
Exception in thread drain-hsdev stdout:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "/my_user_path/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/hsdev.py", line 555, in run
    l = decode_bytes(self.fd.readline()).rstrip()
  File "./python3.3/encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 92: ordinal not in range(128)
```

**Comment by bscottm** [comment]
Will fix the `ProcHelper` bug (easy fix, although, really, I did test it.) Not sure about the `UnicodeDecodeError`.

**Comment by bscottm** [comment]
`filter_command.py` is related to using an indenter. Which one were you using?

**Comment by xldenis** [comment]
I have `stylish-haskell` installed and available on the `$PATH`.

**Comment by bscottm** [comment]
Yeah. Just staring at the code on the current `master` branch -- it's an obvious bug. I've already fixed this, but haven't updated the `master` branch with a new release, pending an answer in another issue. Hopefully, I can push a new release tomorrow or Wednesday.

**Comment by bscottm** [comment]
Unicode: Do you have a specific locale set or are you using UTF-8?

**Comment by xldenis** [comment]
I'd be fine with testing a branch if you can show me how. As for locale, it's set to `en_CA.UTF-8`.

**Comment by bscottm** [comment]
- Uninstall the SublimeHaskell plugin (`PackageManager: Remove package`)
- Then use `git` to manually install the plugin:

```shell
    pushd "~/Library/Application Support/Sublime Text 3/Packages"
    git clone https://github.com/bscottm/SublimeHaskell.git
    cd SublimeHaskell
    git checkout reactive_output
    popd
```

The branch's name is `reactive_output`. You can get back to the `master` branch (the current release version):

```shell
    pushd "~/Library/Application Support/Sublime Text 3/Packages"
    git checkout master
    popd
```

You can also completely remove the directory and use `Package Manager` to re-install the released plugin.

**Comment by xldenis** [comment]
I've tested it lat night, definitely seems to crash less however, I still get errors with `Show Types` 

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "/userpath/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/types.py", line 332, in run
    result = self.get_types(filename, int(line) if line else None, int(column) if column else None)
  File "/userpath/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/types.py", line 255, in get_types
    return get_type(self.view, filename, module_name, line, column)
  File "/userpath/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/types.py", line 181, in get_type
    return sorted_types(view, ts, pt)
  File "/userpath/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/types.py", line 170, in sorted_types
    list(filter(lambda t: t.region(view).contains(pt), types)),
TypeError: 'NoneType' object is not iterable
```

and most commands return errors along the lines of:

```
Sublime Haskell: hsdev whois returns error: other error, msg: File '/userpath/path/ill/src/Ill/Parser.hs' not found, id: 12
Sublime Haskell: hsdev lookup returns error: other error, msg: File '/userpath/path/ill/src/Ill/Parser.hs' not found, id: 13
```

However `stylish` works now which is already a big deal to me!

**Comment by bscottm** [comment]
@xldenis: To paraphrase Mike Elkins, author of the 'mutt' mail client: "All versions of SublimeHaskell suck, this one just sucks less"? :-)

The Python error I can fix fairly easily, at least to ensure that plugin handles the unexpected. The `hsdev` errors probably need @mvoidex to diagnose.

**Comment by xldenis** [comment]
> To paraphrase Mike Elkins, author of the 'mutt' mail client: "All versions of SublimeHaskell suck, this one just sucks less"? :-)

For sure! Being able to run Stylish from ST is already pretty huge for me, but having the `Show Types` feature working would be _amazing_

**Comment by bscottm** [comment]
@xldenis: Show Types -> works for me on a Haskell file that has no errors. The 'NoneType is not iterable' error is fixed.

    pushd "~/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell"
    git pull
    popd

**Comment by xldenis** [comment]
It doesn't work for me and the file has no errors since `stack clean && stack build` works fine without errors. 

The only log produced is

```
<hsdev stdout> 15/03/17 14:05:24 -0500	WARN	<socket: 28>/<socket: 28>> Invalid request {"ghc-opts":["-i /Users/xavier/Code/xldenis/ill"],"files":[{"file":"/Users/xavier/Code/xldenis/ill/src/Ill/Parser.hs","contents":null}],"id":"208","command":"types","no-file":true}
```

**Comment by bscottm** [comment]
@xldenis: Have you updated `hsdev` recently?

**Comment by xldenis** [comment]
I'm running `0.2.0.0`, since it isn't included in any more recent stackage lts releases.

**Comment by bscottm** [comment]
@xldenis: Copy the following and save as `stack.yaml` in `hsdev`'s top-level directory:

```yaml
flags: {}
extra-package-dbs: []
packages:
- location: '.'
- location: tests\test-package\
extra-deps:
- aeson-lens-0.5.0.0
- haskell-src-exts-1.19.1
- hdocs-0.5.1.0
- hlint-1.9.41
- simple-log-0.5.1
resolver: lts-7.20
```

Build using `stack build --install-ghc`, because the resolver wants to use ghc-8.0.1 and `--install-ghc` will install a _local_ ghc, not use your system ghc.

**Comment by xldenis** [comment]
using 

```
flags: {}
packages: []
extra-deps:
  - hdocs-0.5.1.0
  - hsdev-0.2.2.0
packages:
  - location:
      git: https://github.com/haskell/haddock
      commit: 240bc38b94ed2d0af27333b23392d03eeb615e82
    subdirs:
      - haddock-api
    extra-dep: true
resolver: lts-8.5
```

in my `.stack/global/config.yml` fixes the build issues! Everything seems to work this is amazing!

**Comment by bscottm** [comment]
@xldenis: New version of plugin pushed. Update and let me know if it sucks less.

**Comment by bscottm** [comment]
@xldenis: Going once...

**Comment by bscottm** [comment]
@xldenis: Going twice...

**Comment by xldenis** [comment]
Oh hey, sorry. The plugin isn't erroring in the same ways, but there seems to be some issues with `hsdev` which can cause it to suck up a ton of CPU time and memory.

**Comment by bscottm** [comment]
@xldenis: I'm going to close this issue because `hsdev` issues belong to the `hsdev` project.

**Comment by xldenis** [comment]
Yep, agreed.
